// This file is no longer the primary source for database types if using Prisma.
// Prisma generates its own client and types based on your prisma/schema.prisma file.
// You can safely remove this file if you are exclusively using Prisma for database interactions.
//
// If you plan to use Supabase client for features like Auth or Realtime alongside Prisma,
// you might still generate types here using the Supabase CLI for those specific Supabase interactions,
// but it won't reflect your Prisma schema directly.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Placeholder - this structure would be generated by `npx supabase gen types typescript`
// if you were using Supabase directly for database schema management.
export type Database = {
  public: {
    Tables: {
      // Example:
      // tests: {
      //   Row: { /* ... */ }
      //   Insert: { /* ... */ }
      //   Update: { /* ... */ }
      //   Relationships: []
      // }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
